### ISSUE TITLE
go web server framework discussion

### ISSUE THREAD

**Issue by Cyberhan123** [netless-io/flat-server#429]
Which is the most suitable framework?
1. go mirco
2. gin
3. gf (go frame)
4. go native
5. echo

After my use and research, gin and echo are more similar to koa，they are faster and lighter,but not strong enough to build an cloud native appliction with unsound toolset, they can't track error or report log etc...
So gf is coming, and it has been verified by multiple companies, and also have full utils library.
@BlackHole1 what's your opinion?

**Comment by BlackHole1** [comment]
@berryhe

**Comment by berryhe** [comment]
thank you for your suggestions. 

choosing a suitable framework can really help us solve many problems quickly。we have considered many other things when choosing the server framework. 
eg: gin、httprouter、iris、echo、gf、go-kit、go-mirco。

first of all, we think of a server framework that only needs routing functions. There should not be too many heavy functions in it

at that time we might consider httprouter, he is simple and efficient, but he is not suitable for quickly integrating some middleware.

so we finally decided to use gin, because it is simple and just right. We will choose some suitable libraries to integrate the other functions we need, Instead of importing a huge framework to try to solve all our problems

there is no silver bullet, right?
@Cyberhan123

**Comment by Cyberhan123** [comment]
、


> thank you for your suggestions.
> 
> choosing a suitable framework can really help us solve many problems quickly。we have considered many other things when choosing the server framework. eg: gin、httprouter、iris、echo、gf、go-kit、go-mirco。
> 
> first of all, we think of a server framework that only needs routing functions. There should not be too many heavy functions in it
> 
> at that time we might consider httprouter, he is simple and efficient, but he is not suitable for quickly integrating some middleware.
> 
> so we finally decided to use gin, because it is simple and just right. We will choose some suitable libraries to integrate the other functions we need, Instead of importing a huge framework to try to solve all our problems
> 
> there is no silver bullet, right? @Cyberhan123

Respect your choice
