### ISSUE TITLE
How can we establish a connection between the server and the client, and designate the host in the process?

### ISSUE THREAD

**Issue by zerohct** [netless-io/flat-server#830]
I see that the flat process is running via Vitejs, and it includes Until.js for choosing between configurations for CN or SG  . Additionally, how can I designate the host for both, particularly when attempting to connect Flat with Flat Server through Laragon? I've attempted this but haven't been successful. Thank you very much.

**Comment by hyrious** [comment]
I don't use Laragon so I don't know. However the Flat client (web) is a static website. You can refer to its `web/flat-web/deploy/nginx` folder to see how it is routed. It is the same as many other single-page applications.

**Comment by zerohct** [comment]
Which applications do you use to connect the web, server, host, and database?

**Comment by hyrious** [comment]
Do they need any applications? They are just services running on servers and binding to different hosts and ports. They communicate with each other using standard HTTP(S) protocols.

The server (this repo) obviously must use `Node.js` to run since it depends on many Node.js runtime features.

The client (web) is just a static website as I mentioned above. It can be served by many tools/services. Like `nginx`, vercel, netlify, github-pages, anything that acts as an http server.

The databases are standalone softwares, they just run by themselves.

The hostname is often configured by the domain service, and is often backended by an nginx service to support serving SSL certificates that enables HTTPS.

**Comment by zerohct** [comment]
How can I improve my chances of successfully fetching clients with the server?
![image](https://github.com/netless-io/flat-server/assets/100672288/58d8f1c4-3dd3-4f01-acac-4df60c99b87c)

**Comment by zerohct** [comment]
i repair this 
![image](https://github.com/netless-io/flat-server/assets/100672288/2bf8dce1-e69c-4fe1-9447-a01f9f9ebfc4)
![image](https://github.com/netless-io/flat-server/assets/100672288/645bd714-16ba-4e01-9935-3399eb5d3f7a)
What did I do wrong?

**Comment by hyrious** [comment]
Possible reasons:

- Port `80` is special which is often protected by the firewall. You can test the server manually by opening http://localhost:80 in the browser to see if it is connected and get a response. If it is blocked by your firewall, you can change the port to another.

- The code in Flat [intentionally formats the final URL in HTTPS](https://github.com/netless-io/flat/blob/main/packages/flat-server-api/src/constants.ts#L12-L15) protocol. However the server only serves behind the HTTP (not HTTPS) protocol. So you have to modify the code to test the server locally.

**Comment by zerohct** [comment]
Like this, but it doesn't work.
![image](https://github.com/netless-io/flat-server/assets/100672288/9b145596-ad5c-4297-9974-85c6476d38e7)
![image](https://github.com/netless-io/flat-server/assets/100672288/5e58589a-6d53-4c48-9550-fd1799cd0de2)
![image](https://github.com/netless-io/flat-server/assets/100672288/8225e858-78b9-41c5-ab79-f9e1ffd2108e)
![image](https://github.com/netless-io/flat-server/assets/100672288/d6e7105a-61ae-4f1a-9ccf-594a236adff2)
![image](https://github.com/netless-io/flat-server/assets/100672288/106a2dad-8d58-4dc5-8392-2635c6d26184)
![image](https://github.com/netless-io/flat-server/assets/100672288/7e3281ee-3a8f-4bcd-8dd1-9d9d36b71b1e)

**Comment by zerohct** [comment]
Thank you, my professor.
